# Generated by Django 4.0.3 on 2022-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_validated_customuser_submited_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_personalInfo',
            field=models.BooleanField(default=False),
        ),
    ]
