# Generated by Django 4.0.3 on 2022-04-01 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_has_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('employment', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('crypto_source', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
