# Generated by Django 4.0.3 on 2022-04-02 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_personalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='submited_docs',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='user',
        ),
        migrations.CreateModel(
            name='DocumentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('ticket_type', models.CharField(max_length=255)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.documentticket'),
            preserve_default=False,
        ),
    ]
