# Generated by Django 3.1.3 on 2022-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220402_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentticket',
            name='api_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentticket',
            name='document_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentticket',
            name='match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentticket',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
