# Generated by Django 3.1.3 on 2022-04-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220405_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cus_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
