# Generated by Django 3.1.3 on 2022-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_cus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='postal',
            field=models.CharField(max_length=255),
        ),
    ]
