# Generated by Django 3.2.12 on 2022-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_depositdocs_depositticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentticket',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
