# Generated by Django 3.2.12 on 2022-05-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_documentticket_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
