# Generated by Django 3.2.12 on 2022-05-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_balance_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
