# Generated by Django 3.2.12 on 2022-05-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_balance_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='network',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='balance',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
            preserve_default=False,
        ),
    ]
