# Generated by Django 3.2.12 on 2022-05-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220502_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='decimals',
            field=models.IntegerField(default=18),
        ),
    ]
