# Generated by Django 3.2.12 on 2022-05-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='d_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='e_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='w_fee',
            field=models.FloatField(default=0),
        ),
    ]
