# Generated by Django 3.2.12 on 2022-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220503_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ust_label', models.CharField(default='', max_length=255)),
                ('disable_ust_withdrawals', models.BooleanField(default=True)),
            ],
        ),
    ]
