# Generated by Django 3.2.12 on 2022-05-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_withdrawsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='usd_value',
            field=models.FloatField(default=0),
        ),
    ]
