# Generated by Django 3.2.12 on 2022-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_tickets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawsettings',
            name='disable_ust_sweep',
            field=models.BooleanField(default=True),
        ),
    ]
