# Generated by Django 3.2.12 on 2022-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_coin_admin_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('chainId', models.IntegerField(default=0)),
                ('token_fee', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coin',
            name='token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickets',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
