# Generated by Django 3.2.12 on 2022-05-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220519_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.networks'),
        ),
    ]
