# Generated by Django 3.2.12 on 2022-05-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_coin_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='idd',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
