# Generated by Django 3.2.12 on 2022-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_transactions_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
