# Generated by Django 3.2.12 on 2022-05-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='spread',
            field=models.FloatField(default=0),
        ),
    ]
