# Generated by Django 3.2.12 on 2022-05-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_coin_spread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
