# Generated by Django 3.2.12 on 2022-05-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_balance_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactions')),
            ],
        ),
    ]
