# Generated by Django 3.2.12 on 2022-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20220522_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='kraken_balance',
            field=models.FloatField(default=0),
        ),
    ]
