# Generated by Django 3.2.12 on 2022-05-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_coin_kraken_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='kraken_balance',
            new_name='kraken_fee',
        ),
    ]
