# Generated by Django 3.2.12 on 2022-05-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_kraken_balance_coin_kraken_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.networks'),
        ),
    ]
