# Generated by Django 3.2.12 on 2022-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_coin_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deposit_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
